### ISSUE TITLE
npm run watch

### ISSUE THREAD

**Issue by hsagulo** [salcode/bootstrap4-genesis#18]
npm ERR! Failed at the bootstrap4-genesis@0.1.0 watch script 'gulp watch'.
npm ERR! This is most likely a problem with the bootstrap4-genesis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls bootstrap4-genesis
npm ERR! There is likely additional logging output above.

**Comment by salcode** [comment]
Hi @hsagulo,

Thanks for reporting this. I'm not sure what is causing the issue.

I'm trying to recreate the problem on my machine but I've been unsuccessful thus far. A couple of questions that might help me run this down.

1. Did you run `npm install` before `npm run watch`?

2. What version of npm are you using? (i.e. what do you get when you run `npm --version` from the command line)

3. If you run `node_modules/gulp/bin/gulp.js` from the command line (from the root of the `bootstrap4-genesis` directory), what output do you get?

Thanks.

**Comment by hsagulo** [comment]
Hello @salcode, 

Sorry the issue is on my end. I don't have xCode installed on this machine. Thank you so much!
